# Generated by Django 5.2.5 on 2025-08-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('daily_rate', models.FloatField(blank=True, null=True)),
                ('distance_from_home', models.FloatField(blank=True, null=True)),
                ('monthly_income', models.FloatField(blank=True, null=True)),
                ('overtime', models.CharField(blank=True, max_length=10, null=True)),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
