# Generated by Django 5.2.5 on 2025-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnover', '0002_alter_attritionprediction_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='attritionprediction',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
